### PR TITLE
Overlay

### PR DESCRIPTION
**Pull request by ravisha7feb**
Notification after copying the URL of a picture popping up on it.

### CODE REVIEW

**Comment by Ali-Doggaz** [comment]
I think the file extension.js has been wrongly modified by a merge conflict; (Check line 751)

**Comment by Ali-Doggaz** [comment]
I fixed that on my local version to try it out, and the download function isn't working anymore. Normally it should be triggered by a double-click on a picture, but double-clicking isn't trigerring the download anymore 😢

**Comment by ravisha7feb** [comment]
> I fixed that on my local version to try it out, and the download function isn't working anymore. Normally it should be triggered by a double-click on a picture, but double-clicking isn't triggering the download anymore 😢
> You could add an on-click event on the card/overlay that is appearing (the card that contains the "URL copied" message), that triggers the download and shows another card/overlay saying "Picture Downloaded!".

I know where the problem is. The javascript code where you have Copy_Picture_URL(txt), Download(pictureSource), etc. Our function for displaying the notification is right above the Download() code, and I don't know why but whenever I add any Javascript function in that part, the function just below it doesn't work. That's why Download() function isn't working, because I placed it just below the function overlay, which is actually another issue that can be worked on.
I'll try to fix this by placing code snippets in a way that all JS functions work.
About the Picture Downloaded thing, I'll try adding that too.
Thanks for feedback

**Comment by Ali-Doggaz** [comment]
Looks amazing!

**Review by Ali-Doggaz — COMMENTED** [review]
Everything looks good!

**Pull request merged**
